apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-study-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: case-study-app
  template:
    metadata:
      labels:
        app: case-study-app
    spec:
      containers:
      - name: app
        image: case-study-app:latest
        ports:
        - containerPort: 3000
