apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-case-study
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-case-study
  template:
    metadata:
      labels:
        app: docker-case-study
    spec:
      containers:
      - name: docker-case-study
        image: 233125067005.dkr.ecr.ap-south-1.amazonaws.com/docker-case-study:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
