apiVersion: v1
kind: Service
metadata:
  name: docker-case-study
  namespace: default
spec:
  selector:
    app: docker-case-study
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
